name: Interstate Bank Developers
favicon: null
layout_spectrum: 0.3692921958863735
typography_spectrum: 0.9151085368357599
title: 'An Ideal Time to Start a Bank!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.75
  lightness: 0.3752442162949592
  saturation: 0.03890812024474144
  rhythmicContrast: 0.8266398997511715
purpose: []
